#!/bin/bash
python train_vidreid_xent_htri.py -d mars \
                                  --seq-len 8 \
                                  --train-batch 16 \
                                  --test-batch 16 \
                                  --num-instances 4 \
                                  --train-sample restricted \
                                  --test-sample evenly \
                                  --train-sampler RandomIdentitySamplerV1 \
                                  --optim adam \
                                  --soft-margin \
                                  --max-epoch 200 \
                                  --lr 1e-4 \
                                  --stepsize 50 100 150 \
                                  -a resnet50_s1 \
                                  --flip-aug \
                                  --print-last \
                                  --gpu-devices 1 \
                                  --eval-step 5 \
                                  --dist-metric cosine \
                                  --save-dir log/video/resnet50_s1/mars
