#!/bin/bash
python train_vidreid_xent_htri.py -d mars \
                                  --seq-len 4 \
                                  --train-batch 64 \
                                  --test-batch 64 \
                                  --num-instances 4 \
                                  --train-sample restricted \
                                  --test-sample evenly \
                                  --train-sampler RandomIdentitySampler \
                                  --optim adam \
                                  --max-epoch 600 \
                                  --lr 3e-4 \
                                  --stepsize 200 400 \
                                  --zero-wd 70 \
                                  -a sta \
                                  --flip-aug \
                                  --print-last \
                                  --gpu-devices 2,3 \
                                  --eval-step 5 \
                                  --start-eval 50 \
                                  --save-dir log/video/sta/mars
