#!/bin/bash
python train_vidreid_xent_htri.py -d mars \
                                  --seq-len 4 \
                                  --train-batch 64 \
                                  --test-batch 64 \
                                  --num-instances 4 \
                                  --train-sample restricted \
                                  --test-sample evenly \
                                  --train-sampler RandomIdentitySampler \
                                  --optim adam \
                                  --soft-margin \
                                  --max-epoch 400 \
                                  --lr 1e-4 \
                                  --stepsize 100 200 300 \
                                  -a gsta \
                                  --flip-aug \
                                  --print-last \
                                  --gpu-devices 0,1 \
                                  --eval-step 5 \
                                  --dist-metric cosine \
                                  --save-dir log/video/gsta/mars
